# Generated by Django 5.1.6 on 2025-02-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.CharField(max_length=20, unique=True)),
                ('estado_matricula', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='leiloeiro',
            fields=[
                ('leiloeiro_nome', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('leiloeiro_cpf', models.CharField(default='', max_length=150)),
                ('leiloeiro_email', models.EmailField(default='', max_length=254)),
                ('leiloeiro_fone', models.CharField(default='', max_length=150)),
                ('leiloeiro_site', models.URLField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('leiloeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.leiloeiro')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.matricula')),
            ],
        ),
    ]
